CREATE TABLE T_ATS_UPDATE_GHJ
(
  ID NUMBER NOT NULL,
  VERSION VARCHAR2(15) NOT NULL,
  UPLOAD_USER VARCHAR2(20),
  UPDATE_TIME DATE,
  FILE_NAME VARCHAR2(100),
  FILE_DESC VARCHAR2(1000),
  UPLOAD_FILE BLOB
, CONSTRAINT T_ATS_UPDATE_GHJ_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
;

ALTER TABLE T_ATS_UPDATE_GHJ
ADD CONSTRAINT T_ATS_UPDATE_GHJ_UK UNIQUE
(
  VERSION
)
 ENABLE
;
